import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavbarWithCTAButton from "./NavbarWithCTAButton";
import DefaultFooter from "./DefaultFooter";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavbarWithCTAButton />
        <div className="p-10">{children}</div>
        <DefaultFooter />
      </body>
    </html>
  );
}
